name: 'Called ADF Deploy Action'
description: 'This action deploys the ARM template for Azure Data Factory'

inputs:
  resource-group-name:
    description: 'The name of the resource group'
    required: true
  data-factory-name:
    description: 'The name of the Azure Data Factory'
    required: true
  arm-template-file:
    description: 'The name of the ARM template file'
    required: true
  arm-template-parameters-file:
    description: 'The name of the ARM template parameters file'
    required: true
  azure-client-id:
    description: 'The Azure client id'
    required: true
  azure-tenant-id:
    description: 'The Azure tenant id'
    required: true
  azure-subscription-id:
    description: 'The Azure subscription id'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Azure Login'
      uses: azure/login@hf_447_release
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }} 
        enable-AzPSSession: true
          
    - name: 'Download a single artifact'
      uses: actions/download-artifact@v3
      with:
        name: datafactory

    - name: 'Install Az PowerShell module'
      run: if('${{ inputs.skipAzModuleInstallation }}' -ne 'true') { Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force }
      shell: pwsh

    - name: 'Run Pre-deployment script'
      run: |
        ${{ github.workspace }}/PrePostDeploymentScript.ps1 `
          -armTemplate '${{ format('{0}/{1}', github.workspace, inputs.arm-template-file) }}' `
          -armTemplateParameters '${{ format('{0}/cicd-parameters/{1}', github.workspace, inputs.arm-template-parameters-file) }}' `
          -ResourceGroupName '${{ inputs.resource-group-name }}' `
          -DataFactoryName '${{ inputs.data-factory-name }}' `
          -predeployment $true `
          -deleteDeployment $false
      shell: pwsh

    - name: Create deployment stack
      run: |
        az stack group create --name "Deploy ARM Template in Deployment Stack" \
          -action-onunmanage deleteAll \
          -deny-settings-mode denyDelete \
          -resource-group ${{ inputs.resource-group-name }} \
          -template-file ${{ format('{0}/{1}', github.workspace, inputs.arm-template-file) }} \
          -parameters ${{ format('{0}/cicd-parameters/{1}', github.workspace, inputs.arm-template-parameters-file) }} \
          -yes
      shell: pwsh

    - name: 'Run Post-deployment script'
      run: |
         ${{ github.workspace }}/PrePostDeploymentScript.ps1 `
          -armTemplate '${{ format('{0}/{1}', github.workspace, inputs.arm-template-file) }}' `
          -armTemplateParameters '${{ format('{0}/cicd-parameters/{1}', github.workspace, inputs.arm-template-parameters-file) }}' `
          -ResourceGroupName '${{ inputs.resource-group-name }}' `
          -DataFactoryName '${{ inputs.data-factory-name }}' `
          -predeployment $false `
      shell: pwsh

    - name: 'Azure CLI script'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
