name: 'Called ADF Deploy Action'
description: 'This action deploys the ARM template for Azure Data Factory'

inputs:
  resource-group-name:
    description: 'The name of the resource group'
    required: true
  data-factory-name:
    description: 'The name of the Azure Data Factory'
    required: true
  arm-template-file:
    description: 'The name of the ARM template file'
    required: true
  arm-template-parameters-file:
    description: 'The name of the ARM template parameters file'
    required: true

permissions:
  id-token: write
  contents: read

runs:
  using: 'composite'
  steps:
    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true
          
    - name: 'Download a single artifact'
      uses: actions/download-artifact@v3
      with:
        name: datafactory

    - name: 'Install Az PowerShell module'
      run: if('${{ inputs.skipAzModuleInstallation }}' -ne 'true') { Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force }
      shell: pwsh

    - name: 'Run Pre-deployment script'
      description: 'Run the pre-deployment script generated by the ADF Publish Action and npm package'
      run: |
        ${{ github.workspace }}/PrePostDeploymentScript.ps1 `
          -armTemplate '${{ format('{0}/{1}', github.workspace, inputs.arm-template-file) }}' `
          -ResourceGroupName '${{ inputs.resource-group-name }}' `
          -DataFactoryName '${{ inputs.data-factory-name }}' `
          -predeployment $true `
          -deleteDeployment $false
      shell: pwsh

    - name: 'Deploy ARM Template'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create --resource-group ${{ inputs.resource-group-name }} --template-file ${{ format('{0}/{1}', github.workspace, inputs.arm-template-file) }} --parameters ${{ format('{0}/{1}', github.workspace, inputs.arm-template-parameters-file) }} --mode Incremental

    # - name: Deploy resources
    #   uses: Azure/data-factory-deploy-action@v1.2.0
    #   with:
    #     resourceGroupName: ${{ inputs.resource-group-name }}
    #     dataFactoryName: ${{ inputs.data-factory-name }}
    #     armTemplateFile: ${{ format('{0}/{1}', github.workspace, inputs.arm-template-file) }}
    #     armTemplateParametersFile: ${{ format('{0}/{1}', 'cicd-parameters', inputs.arm-template-parameters-file) }}

    - name: 'Run Post-deployment script'
      description: 'Run the post-deployment script generated by the ADF Publish Action and npm package'
      run: |
         ${{ github.workspace }}/PrePostDeploymentScript.ps1 `
          -armTemplate '${{ format('{0}/{1}', github.workspace, inputs.arm-template-file) }}' `
          -ResourceGroupName '${{ inputs.resource-group-name }}' `
          -DataFactoryName '${{ inputs.data-factory-name }}' `
          -predeployment $false `
      shell: pwsh

    - name: 'Azure CLI script'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
