name: 'Called ADF Deploy Action'
description: 'This action deploys the ARM template for Azure Data Factory'

inputs:
  resource-group-name:
    description: 'The name of the resource group'
    required: true
  data-factory-name:
    description: 'The name of the Azure Data Factory'
    required: true
  arm-template-file:
    description: 'The name of the ARM template file'
    required: true
  arm-template-parameters-file:
    description: 'The name of the ARM template parameters file'
    required: true
  azure-credentials:
    description: 'The Azure credentials'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}
        enable-AzPSSession: true
          
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: datafactory

    - name: Deploy resources
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: ${{ inputs.resource-group-name }}
        dataFactoryName: ${{ inputs.data-factory-name }}
        armTemplateFile: ${{ format('{0}/{1}', github.workspace, inputs.arm-template-file) }}
        armTemplateParametersFile: ${{ format('{0}/{1}', 'azuredatafactory/cicd-parameters', inputs.arm-template-parameters-file) }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
